---
# golangci-lint configuration for wink CLI
# Constitution requirement: Code Quality First

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo      # Cyclomatic complexity ≤10 per constitution
    - misspell
    - gocritic
    - gosec        # Security issues
    - revive
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 10  # Constitution: Cyclomatic complexity ≤10

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  gosec:
    excludes:
      - G204  # Allow subprocess execution (needed for run_in_terminal tool)

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - errcheck
    - path: tests/
      linters:
        - gocyclo
        - gosec
